#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile.cpu
  image: pomelo925/paperviz:cpu

  volumes:
    # GUI support for visualization (optional, for display windows)
    - "${XAUTHORITY:-$HOME/.Xauthority}:${XAUTHORITY:-/root/.Xauthority}"
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "/etc/localtime:/etc/localtime:ro"

    # Workspace volumes - mount local files into container
    - "../workspace:/workspace"

  environment:
    - DISPLAY=${DISPLAY}

  user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
  
  network_mode: "host"
  ipc: host
  
  stdin_open: true
  tty: true
  stop_grace_period: 1s
  working_dir: /workspace

##############################
###   Container Services   ###
##############################
services:
  manim:
    <<: *common
    container_name: paperviz-manim
    command: ["/bin/bash"]